// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ZdsvBLk9OneHWfyWpfQUGfZC1LPsXhQ',
    appId: '1:971933564478:web:221383dafec386c7675b6f',
    messagingSenderId: '971933564478',
    projectId: 'watchhistoryreminder',
    authDomain: 'watchhistoryreminder.firebaseapp.com',
    storageBucket: 'watchhistoryreminder.firebasestorage.app',
    measurementId: 'G-KH6WQGBBRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXtciriva1meDXOctwk277m5vnGzThCI',
    appId: '1:971933564478:android:c56e994084965f9b675b6f',
    messagingSenderId: '971933564478',
    projectId: 'watchhistoryreminder',
    storageBucket: 'watchhistoryreminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMBkk_aNNzE_8YWzP9Ry9hsdKjzqleB0',
    appId: '1:971933564478:ios:a46a46701bc5ffb5675b6f',
    messagingSenderId: '971933564478',
    projectId: 'watchhistoryreminder',
    storageBucket: 'watchhistoryreminder.firebasestorage.app',
    iosBundleId: 'come.watchhistoryreminder.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSMBkk_aNNzE_8YWzP9Ry9hsdKjzqleB0',
    appId: '1:971933564478:ios:a46a46701bc5ffb5675b6f',
    messagingSenderId: '971933564478',
    projectId: 'watchhistoryreminder',
    storageBucket: 'watchhistoryreminder.firebasestorage.app',
    iosBundleId: 'come.watchhistoryreminder.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ZdsvBLk9OneHWfyWpfQUGfZC1LPsXhQ',
    appId: '1:971933564478:web:221383dafec386c7675b6f',
    messagingSenderId: '971933564478',
    projectId: 'watchhistoryreminder',
    authDomain: 'watchhistoryreminder.firebaseapp.com',
    storageBucket: 'watchhistoryreminder.firebasestorage.app',
  );
}

